package common

// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/Evrynetlabs/evrhub/x/common/querier
// ALIASGEN: github.com/Evrynetlabs/evrhub/x/common/types

import (
	"github.com/Evrynetlabs/evrhub/x/common/types"
)

var (
	// functions aliases
	NewEthereumAddress                = types.NewEthereumAddress
)

type (
	EthereumAddress          = types.EthereumAddress
	EvrnetAddress            = types.EvrnetAddress
)
